package com.spring.mapper;

import com.spring.pojo.Role;
import com.spring.pojo.User_RoleExample;
import com.spring.pojo.User_RoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User_RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Apr 06 11:17:14 CST 2022
     */
    int countByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Apr 06 11:17:14 CST 2022
     */
    int deleteByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Apr 06 11:17:14 CST 2022
     */
    int deleteByPrimaryKey(User_RoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Apr 06 11:17:14 CST 2022
     */
    int insert(@Param("userId") Long userId, @Param("roleIds") Long[] roleIds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Apr 06 11:17:14 CST 2022
     */
    int insertSelective(User_RoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Apr 06 11:17:14 CST 2022
     */
    List<User_RoleKey> selectByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Apr 06 11:17:14 CST 2022
     */
    int updateByExampleSelective(@Param("record") User_RoleKey record, @Param("example") User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Apr 06 11:17:14 CST 2022
     */
    int updateByExample(@Param("record") User_RoleKey record, @Param("example") User_RoleExample example);
}